---
- hosts: 172.31.91.92
  become: yes
  tasks:
  - name: i want to download a warfile
    get_url:
      url: https://get.jenkins.io/war/2.325/jenkins.war
      dest: /home/ubuntu/jenkins
      force_basic_auth: yes