---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to install a webserver on ubuntu nodes
    apt:
      name: apache22
      state: present
    when: ansible_os_family == "Debian"
    ignore_error: yes
  - name: i want to start a webserver on ubuntu nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
  - name: i want to install a webserver on RedHat nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: i want to start a webserver on RedHat
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  - name: i want to install git
    apt:
      name: git
      state: present
    when: ansible_os_family == "Debian"
  - name: i want to install git
    yum:
      name: git
      state: present
    when: ansible_os_family == "RedHat"

