---
- hosts: 172.31.91.92
  become: yes
  tasks:
  - name: i want to run linux command
    command: hostname -f
    register: myresult
  - name: i want to see my results
    debug:
      msg: "{{myresult}}"