---
- hosts: all
  become: yes
  tasks:
  - name: i want to install a webserver by ubuntu server
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debian"  
  - name: i want to starte a webserver as a ubuntu server
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"  
  - name: i want to install a webserver by RedHat server
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
  - name: i want to start a webserver as RedHat server
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"
