---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to install git
    apt:
      name: git
      state: present
    tags: git
    when: ansible_os_family == "Debian"
  
  - name: i want to install git
    yum:
      name: git
      state: present
    tags: git
    when: ansible_os_family == "RedHat"

  - name: i want to install wget
    apt:
      name: wget
      state: present
    tags: wget
    when: ansible_os_family == "Debian"

  - name: i want to install wget
    yum:
      name: wget
      state: present
    tags: wget
    when: ansible_os_family == "RedHat"

  - name: i want to install tree
    apt:
      name: tree
      state: present
    tags: tree
    when: ansible_os_family == "Debian"

  - name: i want to install tree
    yum:
      name: tree
      state: present
    tags: tree
    when: ansible_os_family == "RedHat"
    
