---
- hosts: all
  become: yes
  tasks:
  - name: i want to install ubuntu server on my node 01
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: i want to start my ubuntu server on my node 01
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
  - name: i want to install RedHat server on my node 02
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
  - name: i want to start my RedHat server on my node 02
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"
