---
- hosts: 172.31.91.92
  become: yes
  vars:
    myvar1: wget
    myvar2: tree
  tasks:
  - name: i want to install git
    apt:
      name: "{{myvar1}}"
      state: present
    when: ansible_os_family == "Debian"

  - name: i want to install tree
    yum:
      name: "{{myvar2}}"
      state: present
    when: ansible_os_family == "RedHat"
