---
- hosts: 172.31.91.92
  become: yes
  tasks:
  - name: i want to install a webserver on ubuntu node
    apt:
      name: apache2
      state: present
  - name: i want to start my webserver on ubuntu node
    service:
      name: apache2
      state: started
  - name: i want to install java on my ubuntu node
    apt:
      name: openjdk-9-jdk
      state: present