---
- hosts: 172.31.91.92
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
  - name: i want to start apache2
    service:
      name: apache2
      state: started
  - name: change the index file to my own data
    template:
      src: indexfile.j2
      dest: /var/www/html/index.html